name: Server - .NET Core

on: [push]

jobs:
  server-build-test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      working-directory: ./portableSEAL
      run: dotnet build --configuration Release
    - name: Unit test
      working-directory: ./portableSEAL
      run: dotnet test --verbosity normal
